sources:
  - ../../NetworkKit/Classes/
templates:
  - ./SourceryTemplates/AutoMockable.stencil
output:
  ../../Tests/GeneratedMocks/NetworkKitMocks.swift
args:
  autoMockableTestableImports: ["NetworkKit"]