use_frameworks!

platform :ios, '13.0'

target 'NetworkKit_Example' do
  pod 'NetworkKit', :path => '../'
  pod 'Alamofire'
  pod 'FoundationKit', :path => '../../FoundationKit'


  target 'NetworkKit_Tests' do
    inherit! :search_paths

    
  end
end
