sources:
  - ../MVVMBoxing
templates:
  - ./SourceryTemplates/AutoMockable.stencil
output:
  ../MVVMBoxingTests/GeneratedMocks/MVVMBoxingMocks.swift
args:
  autoMockableTestableImports: ["MVVMBoxing"]