use_frameworks!

platform :ios, '13.0'

target 'FoundationKit_Example' do
  pod 'FoundationKit', :path => '../', :testspecs => ['Tests']

  target 'FoundationKit_Tests' do
    inherit! :search_paths    
  end
end
